[browser]
gatherUsageStats = false

[theme]
primaryColor = "#5E8271"
backgroundColor = "#f6f1d1"
secondaryBackgroundColor = "#e9e4c4"
textColor = "#4a4a4a"
font = "Quicksand"

[runner]
fastReruns = true

[server]
runOnSave = false
headless = false

[client]
toolbarMode = "minimal"
showErrorDetails = false 