[theme]
primaryColor = "#5E8271"
backgroundColor = "#33210a"
secondaryBackgroundColor = "#261705"
textColor = "#FFFFFF"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[deprecation]
showfileUploaderEncoding = false

[global]
developmentMode = false 